### ISSUE TITLE
Empty list of Google Drive items

### ISSUE THREAD

**Issue by davebcn87** [GrahamDennis/GDFileManagerKit#1]
I get this view when I connect my Google Drive account: 

![google drive](https://f.cloud.github.com/assets/477473/1298012/4f22e514-30ed-11e3-8304-1ffa573fd91a.png)

**Comment by GrahamDennis** [comment]
I've fixed this now.

![screen shot 2013-10-10 at 7 43 34 am](https://f.cloud.github.com/assets/103838/1301504/8e88fa6e-3123-11e3-8b71-6dc5119d74d5.png)

**Comment by davebcn87** [comment]
Thank you @GrahamDennis now this is solved. I think that there is another problem in the detail view. When I try to load a file I get a 404. I tried accesing via drive API directly and get the same behavior. Is this happening to your files also?

**Comment by GrahamDennis** [comment]
I was getting 401s not 404s.  I have fixed this problem which required changing the Google Drive API key, so you'll need to re-add your account.

**Comment by GrahamDennis** [comment]
Hi @davebcn87, let me know if you have any problems with the latest commit.
