### ISSUE TITLE
Error when compiling with C++

### ISSUE THREAD

**Issue by odedbendov** [GrahamDennis/GDFileManagerKit#2]
When compiling my own project, I get an error
".../GDFileManagerKit/GDFileManager.h:23:17: Default initialization of an object of const type 'NSString *const'"

![screen shot 2014-01-01 at 5 33 22 pm](https://f.cloud.github.com/assets/1419217/1829760/0a3047da-72fb-11e3-8782-38504c2a8bad.png)

Going by this post, it may be because of C++ (which indeed my project uses), and requires an 'extern' to precede the line.
https://github.com/atomicobject/objection/issues/26

Best,
Oded

**Comment by GrahamDennis** [comment]
Thanks for reporting this.  I've fixed it in commit 7504a091728fd8a2d056de71f0145f738bcaeb64

**Comment by odedbendov** [comment]
Awesome, thanks!
